[[pages]]
path = "/"
screenshotTimestamp = "2026-03-26T16:01:16Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/bc6273ce-6ba2-4f12-904a-544cb04f2b3e/d6c4579f-acb2-4c54-bbc3-abd743a5f044/tMQnwmM"

[[pages]]
path = "/noticias"
screenshotTimestamp = "2026-03-25T21:39:11Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/44391235-2dd9-4eb7-a015-692ba6676ee1/2b892f93-3dbe-41e9-ba46-765f5b346b41/3uqiuYR"

[[pages]]
path = "/transparencia"
screenshotTimestamp = "2026-03-25T22:15:27Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/44391235-2dd9-4eb7-a015-692ba6676ee1/2b892f93-3dbe-41e9-ba46-765f5b346b41/7hzR84L"

[[pages]]
path = "/transparencia/sic"
screenshotTimestamp = "2026-03-25T22:15:38Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/44391235-2dd9-4eb7-a015-692ba6676ee1/2b892f93-3dbe-41e9-ba46-765f5b346b41/xWARzwQ"

[[pages]]
path = "/transparencia/licitacoes"
screenshotTimestamp = "2026-03-25T22:15:40Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/44391235-2dd9-4eb7-a015-692ba6676ee1/2b892f93-3dbe-41e9-ba46-765f5b346b41/McJUA1h"

[[pages]]
path = "/transparencia/despesas"
screenshotTimestamp = "2026-03-25T22:15:50Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/44391235-2dd9-4eb7-a015-692ba6676ee1/2b892f93-3dbe-41e9-ba46-765f5b346b41/exma17P"

[[pages]]
path = "/transparencia/dados-abertos"
screenshotTimestamp = "2026-03-25T22:16:05Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/44391235-2dd9-4eb7-a015-692ba6676ee1/2b892f93-3dbe-41e9-ba46-765f5b346b41/54aII1L"

[[pages]]
path = "/transparencia/servidores"
screenshotTimestamp = "2026-03-25T22:16:07Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/44391235-2dd9-4eb7-a015-692ba6676ee1/2b892f93-3dbe-41e9-ba46-765f5b346b41/UNx4j4C"

[[pages]]
path = "/site-admin/dashboard"
screenshotTimestamp = "2026-03-25T22:33:44Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/44391235-2dd9-4eb7-a015-692ba6676ee1/2b892f93-3dbe-41e9-ba46-765f5b346b41/uKYtMTa"

[[pages]]
path = "/site-admin/noticias"
screenshotTimestamp = "2026-03-25T22:33:53Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/44391235-2dd9-4eb7-a015-692ba6676ee1/2b892f93-3dbe-41e9-ba46-765f5b346b41/ebvGqIa"

[[pages]]
path = "/site-admin/noticias/nova"
screenshotTimestamp = "2026-03-25T22:33:55Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/44391235-2dd9-4eb7-a015-692ba6676ee1/2b892f93-3dbe-41e9-ba46-765f5b346b41/ABXohTi"

[[pages]]
path = "/site-admin/banners"
screenshotTimestamp = "2026-03-25T22:34:21Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/44391235-2dd9-4eb7-a015-692ba6676ee1/2b892f93-3dbe-41e9-ba46-765f5b346b41/Gy9RObW"

[[pages]]
path = "/site-admin/transparencia"
screenshotTimestamp = "2026-03-25T22:34:23Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/44391235-2dd9-4eb7-a015-692ba6676ee1/2b892f93-3dbe-41e9-ba46-765f5b346b41/psFyidI"

[[pages]]
path = "/site-admin/menus"
screenshotTimestamp = "2026-03-25T22:34:32Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/44391235-2dd9-4eb7-a015-692ba6676ee1/2b892f93-3dbe-41e9-ba46-765f5b346b41/TSFWUhi"

[[pages]]
path = "/site-admin/aparencia"
screenshotTimestamp = "2026-03-25T22:34:34Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/44391235-2dd9-4eb7-a015-692ba6676ee1/2b892f93-3dbe-41e9-ba46-765f5b346b41/w767DFE"

[[pages]]
path = "/servidor/contracheque"
screenshotTimestamp = "2026-03-26T16:01:41Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/bc6273ce-6ba2-4f12-904a-544cb04f2b3e/d6c4579f-acb2-4c54-bbc3-abd743a5f044/RzjAra6"

[[pages]]
path = "/servidor/ferias"
screenshotTimestamp = "2026-03-26T15:48:45Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/bc6273ce-6ba2-4f12-904a-544cb04f2b3e/d6c4579f-acb2-4c54-bbc3-abd743a5f044/V2wQgeE"

[[pages]]
path = "/rh/dashboard"
screenshotTimestamp = "2026-03-26T16:01:48Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/bc6273ce-6ba2-4f12-904a-544cb04f2b3e/d6c4579f-acb2-4c54-bbc3-abd743a5f044/l4GJurs"

[[pages]]
path = "/servidor/requerimentos"
screenshotTimestamp = "2026-03-26T15:48:55Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/bc6273ce-6ba2-4f12-904a-544cb04f2b3e/d6c4579f-acb2-4c54-bbc3-abd743a5f044/ZJqqdsV"

[[pages]]
path = "/servidor/vida-funcional"
screenshotTimestamp = "2026-03-26T15:48:57Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/bc6273ce-6ba2-4f12-904a-544cb04f2b3e/d6c4579f-acb2-4c54-bbc3-abd743a5f044/5p3dozN"

[[pages]]
path = "/servidor/contracheque/3/2026"
screenshotTimestamp = "2026-03-26T15:49:05Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/bc6273ce-6ba2-4f12-904a-544cb04f2b3e/d6c4579f-acb2-4c54-bbc3-abd743a5f044/EzjSGwT"

[[pages]]
path = "/rh/requerimentos"
screenshotTimestamp = "2026-03-26T15:49:07Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/bc6273ce-6ba2-4f12-904a-544cb04f2b3e/d6c4579f-acb2-4c54-bbc3-abd743a5f044/xMffcY9"

[[pages]]
path = "/bi/cockpit"
screenshotTimestamp = "2026-03-26T17:53:37Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/bc6273ce-6ba2-4f12-904a-544cb04f2b3e/d6c4579f-acb2-4c54-bbc3-abd743a5f044/UdWZUNR"

[[pages]]
path = "/bi/financeiro"
screenshotTimestamp = "2026-03-26T17:53:46Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/bc6273ce-6ba2-4f12-904a-544cb04f2b3e/d6c4579f-acb2-4c54-bbc3-abd743a5f044/LQYp8t9"

[[pages]]
path = "/bi/tv"
screenshotTimestamp = "2026-03-26T17:53:49Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/bc6273ce-6ba2-4f12-904a-544cb04f2b3e/d6c4579f-acb2-4c54-bbc3-abd743a5f044/OslBOIE"
